services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - ./infrastructure/mosquitto/config:/mosquitto/config
      - ./infrastructure/mosquitto/data:/mosquitto/data
      - ./infrastructure/mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    depends_on:
      - mqtt
    volumes:
      - ./infrastructure/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Amsterdam  # set this to your current timezone
    devices:
      # Map the USB stick. 
      # you can get this by running ls -l dev/serial/by-id . See README for more
      - /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0:/dev/ttyUSB0
  
  controller:
      build:
        context: .
        dockerfile: src/Dockerfile
      container_name: home_controller
      restart: unless-stopped
      # Privileged is usually required for hardware access (GPU/Input)
      privileged: true
      depends_on:
        - mqtt
        - zigbee2mqtt
      # Host network allows easy access to localhost MQTT and performance
      network_mode: "host"
      environment:
        # CHANGED: Since we use host network, we talk to localhost, not the container name
        - MQTT_ADDRESS=tcp://localhost:1883
        # QT / DISPLAY SETTINGS
        - DISPLAY=:0
        - QT_QPA_PLATFORM=xcb 
        # Fixes some shared memory issues with Qt in Docker
        - QT_X11_NO_MITSHM=1 
        - XDG_RUNTIME_DIR=/tmp
        - QT_QUICK_BACKEND=software
      volumes:
        # Map the X11 socket so we can draw on the screen
        - /tmp/.X11-unix:/tmp/.X11-unix
        # Map input devices (so your touchscreen works)
        - /dev/input:/dev/input
        # Map src to my local src
        - ./src:/app/src
      devices:
        # Pass the GPU through for smooth QML animations
        - /dev/dri:/dev/dri